- src/app/components/MapControlBar.tsx
Closes [Issue 108](https://github.com/CodeForPhilly/vacant-lots-proj/issues/108) by removing the code associated with the search bar from the MapControlBar.tsx component.
Before: 
After:
> Remove Searchbar From MapControlBar.tsx

- src/app/components/PropertyCard.tsx
This PR introduces a new feature in the `PropertyCard` component, adding a direct hyperlink to the City's Atlas website for each listed property.
- An anchor (`<a>`) tag was added to include a hyperlink in the property card.
- The URL for the hyperlink is dynamically generated using the property address and concatenating it with the base URL of the City's Atlas website.
- The hyperlink opens in a new tab (`target="_blank"`) for better user experience and includes `rel="noopener noreferrer"` for improved security.
```
//Added this line:
const atlasUrl = `https://atlas.phila.gov/${ADDRESS}`;
```
```
<div className="p-4">
<div className="font-bold text-xl">{ADDRESS}</div>
<div className="text-gray-700 mb">
{guncrime_density} Crime Rate, {roundedCanopyGap}% Canopy Gap
</div>
// Added this …
```
> Issue #119: Add link to atlas to property cards

- src/app/components/PropertyDetailSection.tsx
- src/app/components/PropertyMap.tsx
- src/app/map/page.tsx
Addresses #88.
To test: go to the Map page, then click on a property.  You should see the corresponding property open in the right sidebar.
OPEN QUESTION: Should we still show the popup?
> Issue 88: opens sidebar from map

- package-lock.json
- src/app/components/PropertyMap.tsx
- src/app/map/page.tsx
Resolves #87.
This PR will make the map focus on the location when an item is clicked from the right menu.
To test this: go to the map screen and click on an item from the right menu, either from grid view or table view.  You should see the map focus on the selected property.
NOTE: I found it a bit hard to see what map item was focused on; I added a feature that opens the tooltip.  Let me know what you think!
> 87 load property into map

- src/app/globals.css
This PR updates the font in the search field to HK Grotesk, like the rest of the site.
> feat: Add font to search field

- src/app/components/LandingPage.tsx
Per #298, this PR changes Find Properties to a link instead of a button nested inside of a link.  I also addressed the Learn More button because it was right there as well.
> feat: Change Find Properties and Learn More to links

- src/app/components/Header.tsx
This PR increases the size of the hitbox of the clickable header links by adding the `href` property to the dropdown, resolving #278.
Before:
After:
> fix: increase link hitbox size

- .eslintrc.json
- eslint-plugin-custom-rules/index.js
- eslint-plugin-custom-rules/package.json
- eslint-plugin-custom-rules/rules/no-text-size-class.js
- package-lock.json
- package.json
- src/app/components/AboutPage.tsx
- src/app/components/FilterView.tsx
- src/app/components/Filters/DimensionFilter.tsx
- src/app/components/Footer.tsx
- src/app/components/GetAccessPage.tsx
- src/app/components/Header.tsx
- src/app/components/IconLink.tsx
- src/app/components/LandingPage.tsx
- src/app/components/MethodologyPage.tsx
- src/app/components/PropertyCard.tsx
- src/app/components/PropertyDetailSection.tsx
- src/app/components/PropertyMap.tsx
- src/app/components/SidePanelControlBar.tsx
- src/app/components/SinglePropertyDetail.tsx
- src/app/components/SinglePropertyInfoCard.tsx
- src/app/components/TakeActionOverviewPage.tsx
- src/app/components/TransformPropertyPage.tsx
- src/app/globals.css
- tsconfig.json
This PR adds an eslint rule to enforce classname usages of `heading-*` and `body-*` classes over `text-*` size classes, and updates the font sizes across the app to conform to this style guide. 
If a user adds tailwind font size classes of `text-sm` to `text-9xl` to any element, they should receive an eslint warning of: ```Use `heading-*` or `body-*` classes instead of specific `text-` size classes.eslint(custom-rules/no-text-size-class)```
Due to the reach of these changes, screenshots won't be explicitly included, but the reviewer should test by opening these files as provided in the acceptance criteria, and seeing that the styles and sizings match (as described in https://github.com/CodeForPhilly/vacant-lots-proj/issues/279):
> - Landing page https://share.cleanshot.com/7zJhPJnB
> - …
> feat(279): refactor text styles and add enforcement via eslint

- src/app/globals.css
This PR updates the mapbox legend to be capitalized and darker. Due to the way this simply linking to the provided mapbox css, it is admittedly very, very brittle — but given that it's understood that it's a ducttape solution, I'll leave it up to the owners of this project to determine if they'd like to merge it in or not.
View the map legend on the main page at `/map`.
Related to (but technically doesn't close) #247
> feat(247): make the mapbox legend more legible

- src/app/components/PropertyMap.tsx
This PR naively sorts the features based on their `priority_value` of "High", "Medium", or "Low".
In the main map at `/map`, zoom tightly into a cross street with all three priority values (of orange, yellow, and green), and see in the filtered results that the properties with the "High Priority" labels are first, with "Medium Priority" second, and "Low" last.
For this example I used N 16th and W Westmoreland, but any set should do.
Closes #293
> feat(293): sort features by priority of high, medium, low

- src/app/globals.css
Updated the global.css file to change the link color to  #0070F0 instead of #3B82F6. 
Issue can be found here: https://github.com/CodeForPhilly/vacant-lots-proj/issues/332
> A11y: All links should use blue #0070F0

- src/app/components/SinglePropertyDetail.tsx
This PR adds styling to stop the Single Property view's table headers from wrapping when the viewport gets too narrow.
From `/map`, click into a single property, and observe the text wrapping headers as you shrink/expand the viewport width.
Closes #305
> feat(305): expand the header width of single property table

- src/app/components/GetAccessPage.tsx
Issue: https://github.com/CodeForPhilly/vacant-lots-proj/issues/372
It seems like the issue was a p tag wasn't inside of the parent div that was causing the error.
> BUG: React/JSX errors on /get-access #372

- src/app/components/TransformPropertyPage.tsx
Issue: https://github.com/CodeForPhilly/vacant-lots-proj/issues/376
It seems like the issue was a p tag that wasn't a parent (changed to a div instead) and a p tag not closed before starting an ul.
> BugFix: React/JSX errors on /transform-property #376

- .gitignore
- src/app/components/PropertyDetailSection.tsx
- src/app/components/PropertyMap.tsx
- src/app/components/SinglePropertyDetail.tsx
- src/app/components/StreetView.tsx
- src/app/map/page.tsx
- src/app/types.tsx
This PR adds a fullscreen Google streetview to the `SinglePropertyDetail` view.
To the reviewer: please note that the way we're generating the embed url is a workaround, and is susceptible to breaking if Google were to ever change how they're structuring their embedding URL.
For how I got the URL in [`StreetView.tsx`](https://github.com/CodeForPhilly/vacant-lots-proj/commit/82f435e6859f57d5d7434ccc6f015a3d98acf394#diff-90f0b4840550f8b5723a8f4b5d882bd090cabdd20fe28f8519994fd61ee9251fR39-R42), I pretty much took a few randomized streetview embed URLs, found the deltas between them, and derived the parameters they're updating to generate the url for the different locations.
Pros to this implementation:
- Free
Cons:
- As far as I know, this url structure isn't documented anywhere and could …
> feat(303): add fullscreen streetview embed to the SinglePropertyDetail view

- src/app/globals.css
This PR increases the font size of of the legend according to the spec described here: https://share.cleanshot.com/2N94qLst
**Before**
**After**
Closes #398
> feat(398): fix map legend font size

- src/app/map/page.tsx
This PR corrects the Street View modal to have it take the full screen, overlaying the navigation bar as well
https://github.com/CodeForPhilly/vacant-lots-proj/assets/8061917/88d7e8ef-16da-4230-a776-1d7dabf79f5f
Closes #396
> feat(396): have streetview modal take full page

- src/app/components/Header.tsx
- src/app/components/MobileNav.tsx
- src/app/globals.css
I used Next UI's NavbarMenuToggle component to add the mobile navigation to the site. I tried to follow the design closely and used many tailwind classes to edit the default component to replicate it. The mobile breakpoint in 640. We should consider a new issue for tablet, which would be between 768px and 1024px I believe.
The DOM order is not accurate. For some reason the menu list is rendering at the end of the page and making the links appear at the end of the tab order when they should appear as the 4th, 5th, and 6th option after selecting the menu to open. This is only on mobile so it's not a huge issue but definitely needs a new issue to correct this as responsive design helps users who zoom in at 300% or more on desktops as well. 
I updated some CSS selectors and adjusted some …
> 259-responsive-nav-feat-css-nav-item-cleanup

- src/components/SidePanelControlBar.tsx
For ticket #413 
Go to the /map page, and zoom out to have more than 1,000 properties. The number should be formatted with a comma between thousands and hundreds.  
Note that the formatting should adapt to the Locale of the browser, meaning that it can change if you are on a VPN to adapt to the country's way of writing numbers (for example 1.500 in France)
@Moylena
> 413 - Format number into string with comma

- src/components/StreetView.tsx
Added title to the iframe element for the Streetview component.
This closes issue https://github.com/CodeForPhilly/vacant-lots-proj/issues/400
I have been having trouble keeping my forked version up to date. Hopefully there are no conflicts.
> 400-add-iframe-title-to-street-view

- src/components/SinglePropertyDetail.tsx
Removed the word link between Atlas and external link icon from the map detail page.
> Removed the word link between Atlas and external link icon #416

- next.config.js
This PR adds a permanent redirect from `/map` to `/find-properties` to ensure any `/map` links don't 404. This also ensures that any Google Search / SEO 'juice' to `/map` doesn't get lost but is also forwarded correctly.
Closes #488
> feat: add redirect from map to find-properties

- src/components/SinglePropertyDetail.tsx
Following the acceptance criteria of https://github.com/CodeForPhilly/vacant-lots-proj/issues/395, this PR makes the Back button of the single property selection pane sticky to the window.
https://github.com/CodeForPhilly/vacant-lots-proj/assets/8061917/5ba2011f-9478-4c19-80c4-2d7435370a70
Closes https://github.com/CodeForPhilly/vacant-lots-proj/issues/395
> feat(395): make property selection back button sticky

- data/docker-compose.yml
- data/src/Pipfile.lock
- data/src/streetview.py
- docs/SETUP/BACK_END.md
- docs/SETUP/FULL_SETUP.md
- src/app/find-properties/[[...opa_id]]/layout.tsx
- src/app/find-properties/[[...opa_id]]/page.tsx
- src/components/FilterView.tsx
- src/components/PropertyCard.tsx
- src/components/PropertyDetailSection.tsx
- src/components/PropertyMap.tsx
- src/components/SidePanelControlBar.tsx
- src/components/SinglePropertyDetail.tsx
I added metadata to the streetview objects in GCP which allows us to essentially use it as a database of sorts. The metadata has location and capture date. You can access it by `OPA_ID` like this:
`https://storage.googleapis.com/storage/v1/b/cleanandgreenphl/o/${opa_id}.jpg`.
I used this to set the URL to change when in a property detail view and allow for deep linking. @thansidwell I'm sure you'll want to add a Share button, will let you mock that up.
I also cleaned up the streetview script so it can run in Docker.
https://www.loom.com/share/9d231645443b476e9aa2568004f38072
> Add metadata to Streetview images, allow deep linking

- src/app/(content-pages)/methodology/MethodologyPage.tsx
- src/app/globals.css
This ticket closes https://github.com/CodeForPhilly/vacant-lots-proj/issues/445
Pulled in content from updated design, https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592%3A31623&mode=design&t=xApEhXaaRt5Yhzxo-1
Included links to resources, updated spacing and mobile responsive spacing. Also added aria labels to warn user of links opening in a new window. I'm not sure if we do that elsewhere on the site or if there is already a preferred method, please let me know if there is! 
**Note:**
I do need the link to the DA's office data but that is not yet available.
> 445-display-content-in-one-column-update-content-links

- src/app/find-properties/[[...opa_id]]/page.tsx
- src/components/PropertyMap.tsx
This PR addresses issue #462 and part of #442 (original: #260, 3 of this [comment](https://github.com/CodeForPhilly/vacant-lots-proj/pull/442#issuecomment-2005564609)). 
Map on initial load is zoomed out to include the rest of the city.  The new map implementation broke one of the expected behaviors in #442 which I resolved along the way. 
https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/85ce56a8-54ac-48a2-a98c-8725525d8e13
https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/719eb4a1-4e2d-422e-9cbf-c49bad387b27
> Fix #462: Changed initial zoom & fixed mobile map

- src/app/(content-pages)/methodology/MethodologyPage.tsx
- src/components/FilterView.tsx
- src/components/Filters/ButtonGroup.tsx
- src/components/Filters/DimensionFilter.tsx
This PR addresses issue #506 which includes:
- Removing icons next to headers
- Rearranging order of the filters
- Adding descriptions for suggested priority and access level
- Clicking on learn more scrolls to respective sections
I also corrected the alignment of the access process filters when they overflow.
https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/4bc69320-2da1-463d-b876-09267c1c4ebd
https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/7dd29e9c-5f12-46ba-967b-d312d92e2689
> Fix #506: Updated filter info 

- src/app/find-properties/[[...opa_id]]/page.tsx
- src/components/PropertyMap.tsx
This addresses issue #486 
When a user searches for a property in the map's search bar, the map shifts to the property and a tooltip appears marking the property.
If the searched-for property is vacant, the side panel changes to the property details.  If the property is not vacant, the side panel remains in the list view or (if it was previously showing another property's details) returns to the list view.
@thansidwell - I don't see any details about whether a zoom level should be set for the search result, so as of now the zoom level does not change when a property is searched.
Also, I thought I saw an assigned ticket that was handling the styling of the map tooltip.  I can't find it now and don't see changes on staging site, so if I was imagining that please let me know and I'll work on …
> 486: Map behavior after property search

- src/components/SinglePropertyDetail.tsx
This closes issue https://github.com/CodeForPhilly/vacant-lots-proj/issues/205
I am resubmitting this PR and I also have removed the extra import for the tooltip component on line 22 "import { Tooltip } from "@nextui-org/react";" from SinglePropertyDetail.tsx
This resolves errors on my local machine, please let me know @brandonfcohen1 if there are any other errors
> 205-header-semantics-and-removing-extra-tooltip-import

- src/components/PropertyAccessOptionContainer.tsx
This PR adds a fix to the logic introduced in https://github.com/CodeForPhilly/vacant-lots-proj/pull/538
You can test this by selecting filters of the properties, and seeing that the properties returned have matching information
https://github.com/CodeForPhilly/vacant-lots-proj/assets/8061917/330cf879-ac33-4b11-a784-ba969f89eb2a
> fix(507): fix "Get Property Access" options logic

- src/app/(content-pages)/transform-property/TransformPropertyPage.tsx
This adds the link to the Gentrification page to the Transform Property Page.
The link is at the bottom of the page with the text "Read more about this topic."
> Add Gentrification Page Link to Transform Property Page

- .eslintrc.json
- package-lock.json
- package.json
- postcss.config.js
- src/app/(content-pages)/legal-disclaimer/LegalDisclaimerPage.tsx
- src/app/(content-pages)/methodology/MethodologyPage.tsx
- src/app/(content-pages)/page.tsx
- src/app/(content-pages)/request-removal/RequestRemovalPage.tsx
- src/app/(content-pages)/take-action-overview/TakeActionOverviewPage.tsx
- src/app/(content-pages)/transform-property/TransformPropertyPage.tsx
- src/app/find-properties/[[...opa_id]]/page.tsx
- src/app/globals.css
- src/app/layout.tsx
- src/components/PropertyDetailSection.tsx
- src/components/PropertyMap.tsx
- src/components/ThemeButton.tsx
- src/components/icons/Rake.tsx
This PR started with addressing the css webpack warnings, but grew to include the following:
- [b3aff59](https://github.com/CodeForPhilly/vacant-lots-proj/pull/574/commits/b3aff5961b6abc1b2b32481205395b07c940e647) : adds `postcss-import` and `-nesting` to handle nested css and silnce the webpack errors
- [6f9b28e](https://github.com/CodeForPhilly/vacant-lots-proj/pull/574/commits/6f9b28e2fef967452b1a56f0cbad7e872f82575f) : fixes the `eslint-plugin-custom-rules` failing to lint by adding the file as a dev dependency. Also adds `"next/core-web-vitals", "plugin:react/recommended", "prettier"` to enforce more consistent styling.
- [7e7e5d4](https://github.com/CodeForPhilly/vacant-lots-proj/pull/574/commits/7e7e5d4b0252e264316c5f8e0c0da24a9bcef6ca) : fixes the linting issues that arose from …
> fix(572): fix webpack warnings + fix linting issues

- src/app/globals.css
- src/components/SinglePropertyDetail.tsx
- This PR restyles the single property detail table to match the figma spec.
- Also fixes the sidepanel border bug described in https://github.com/CodeForPhilly/vacant-lots-proj/issues/566
- Also removes the Access Process as described in 
https://github.com/CodeForPhilly/vacant-lots-proj/issues/567
https://github.com/CodeForPhilly/vacant-lots-proj/assets/8061917/77d8867b-3392-45cc-a24d-17bd7fc79d72
https://github.com/CodeForPhilly/vacant-lots-proj/issues/568
https://github.com/CodeForPhilly/vacant-lots-proj/issues/566
https://github.com/CodeForPhilly/vacant-lots-proj/issues/567
> feat(568): restyle the property table

- src/components/SidePanelControlBar.tsx
This PR adds a Download label to the detail pane button. Hides at the same breakpoint as the Filter button.
https://github.com/CodeForPhilly/vacant-lots-proj/assets/8061917/03711965-3f26-47db-be90-e5c31e27e607
https://github.com/CodeForPhilly/vacant-lots-proj/issues/536
> feat(536): add download button

- src/app/globals.css
- src/components/PropertyMap.tsx
This PR addresses two bugs where you could not click into the map's search field and you could not click the map tooltip. It fixes the bugs by adding `pointer-events: bounding-box' to globals.css for the classes for each of those features:
- maplibregl-ctrl-top-right
- maplibregl-ctrl-bottom-left
I've also added `setSearchedProperty({...searchedProperty, address: "" })` to the map `handleClick` function.  Without that, if the map is clicked on a non-vacant property, the map changes the popup tooltip to the last searched property.
This closes issue #582
> Bug Fix: Map Search Field Not Clickable

- src/app/(content-pages)/about/AboutPage.tsx
- src/app/(content-pages)/transform-property/TransformPropertyPage.tsx
This changes makes the ticket's requested styling changes.
For the About page:
- Increases subheader text size to body-lg
- Decreases margin between image and subheader to 48px
For the Transform Property page:
- Increases margin between subheader and image to 48 px.
- does NOT change anything with margin above page header as that was done seperately
> 561/ Fix Page Content Spacing

- src/components/Header.tsx
- src/components/MobileNav.tsx
This PR addresses issue #525.
I can't edit the padding (px-6) in the header element directly since it's part of the NextUI component. I used negative margins to get 20px in mobile and added 4px to get 28px in desktop.
https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/a39aa907-8401-4c20-a79a-a73ef4480c5f
> Fix #525: Fixed nav padding

- src/app/globals.css
- src/components/FilterView.tsx
- src/components/Filters/DimensionFilter.tsx
- src/components/Filters/Panels.tsx
- src/config/propertyAccessOptions.tsx
This PR request combines the "Access Process", "Conservatorship Eligible", "Side Yard Eligible", and "Tactical Urbanism" into one, new filter section titled "Get Access" which contains six selectable panels: three for access process (private land use agreement, buy from owner, and get from land bank) and one each for conservatorship, side yard, and tactical urbanism.
This PR addresses issue #581 
@thansidwell and @paulhchoi, I have made frontend changes for review in this PR
Some things to note for the reviewers' consideration:
- The 'Find only when its the best option' button from the prototype has not been included because it doesn't seem to add functionality to the filter.  See discussion in issue #581 
- The new panel filter has different functionality than the previous Yes/No button …
> 581 simplify get access filter

- src/app/find-properties/[[...opa_id]]/page.tsx
- src/components/PropertyDetailSection.tsx
- src/components/SidePanelControlBar.tsx
- src/components/SinglePropertyDetail.tsx
This PR fixes the following issues from PR #587 with the feature, "Save properties to local storage":
- UI displays wrong count for "# Properties in View." This PR fixes the issue by showing `savedPropertyCount` instead of  `featureCount` if a user is viewing a list of saved properties.
- Filter button is changing to a selected state and showing a filterCount of "(1)" if a user is filtering by saved properties. This PR fixes the issue by overriding this default behavior and excluding OPA_ID from `filterCount`. Filter button now remains unchanged if user views a list of saved properties. 
https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/9e105ee9-6266-4ef3-8640-71d17b0752a1
Closes #415
> 415: Fix Save button issues

- src/components/Filters/DimensionFilter.tsx
- src/components/Filters/Panels.tsx
This addresses the strobing color issue in #601 
The issue was caused by the filters being re-rendered twice whenever they were selected or deselected.  This PR resolves the issue by putting the `filter` array inside a useMemo that only updates when the `selectedKeys` or `selectedPanelKeys` states change.
https://github.com/CodeForPhilly/clean-and-green-philly/assets/140654473/c583d2c7-1efb-408f-b2d1-dcaf995b69b0
> Bug Fix: Correct flashing of filter button color on select & hover

- .github/workflows/pr_checks.yaml
A quick-and-dirty pipeline to ensure incoming PRs don't introduce any new linting errors and don't break the build. Once merged, the pipeline should fire on every PR that affects the frontend since [GH Actions are enabled by default](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#about-github-actions-permissions-for-your-repository).
> build: first draft of CI pipeline

- src/components/ContentCard.tsx
This PR changes `<h4>` tags to `<h3>` on the Transform Property page, so the page no longer skips heading levels. This improves user accessibility.
This PR changes the tags for both Basic Intervention and Advanced Intervention card titles.
Before PR:
After PR:
Closes #618
> 618: Change card titles to H3 tags on Transform Property page

- src/components/SinglePropertyDetail.tsx
This PR addresses issue #602.
https://github.com/CodeForPhilly/clean-and-green-philly/assets/28910543/36f37ab5-d6dc-40be-9ee2-b9dfe65282f4
> Fix #602: Tooltip for share button when tabbing (a11y) 

- src/app/globals.css
As you can see in the screenshot below, it looks fine and not overflown anymore
Additionally
+ I fixed the **overlapping of copyright (i)  (when opened) with bottom-left legend** on map by raising the position of bottom-left legend a bit only on mobile
solves #598
> Fix the issue of map-legends going offscreen

- src/components/PropertyCard.tsx
Now, when a user is on the Find Properties page and uses their keyboard to tab to focus on a specific card, the background of the entire card will change to gray similar to hovering over the card with a mouse. Previously the background remained white. 
With change:
> 604 /  Apply Hover Styling on Property Cards when Keyboard Focus is on Cards

- src/app/globals.css
- src/components/SinglePropertyDetail.tsx
This PR addresses issue #612 .
I was very limited in what I could modify with the MapLibre library components. It looks like the only way to use NextUI Tooltips is to create custom components. I also played around with the CSS classes and tried displaying elements with :hover to no avail. 
The simplest workaround I found is to style the title attribute tooltip in ::after. There are a couple things to note:
- The default tooltip still shows after few seconds. 
- Centering the tooltips will cause parts of it to be cut off (considered overflow). Changing the z-index didn't seem to help. 
- I haven't tried yet, but I don't think I can modify the title attribute directly (text inside these tooltips).
Edit: Just noticed the tooltip persisting shortly when scrolling in the video, should the …
> Fix #612: Added tooltips for SinglePropertyDetail and MapLegend

- src/app/(content-pages)/layout.tsx
- src/app/CookieProviderWrapper.tsx
- src/app/find-properties/[[...opa_id]]/layout.tsx
- src/app/layout.tsx
- src/components/CookieConsentBanner.tsx
- src/components/Footer.tsx
- src/components/IconLink.tsx
- src/components/SinglePropertyDetail.tsx
- src/context/CookieContext.tsx
This PR creates a cookie consent banner for users to accept or decline cookies in their Web browser.
When user declines cookies and then clicks the "Save Property" button, the property won't be saved. Instead, the cookie-consent banner will appear again and ask for their permission to save cookies in their browser.
Closes #597 
These videos show 3 of the scenarios where the cookie-consent banner will appear:
https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/fd3beb44-841e-4161-8b33-ca67efc229bc
https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/0cafa75e-958b-4ce5-808e-fb1209d2fbaf
> 597: Accept or Decline Cookies

- src/components/SidePanelControlBar.tsx
This PR adds an aria label "Saved Properties" to the Saved button in the map dashboard's side panel.
Closes #624
> 624: Add aria label to Saved button

- src/components/PropertyMap.tsx
This PR adds a bounding box and filter to the mapbox geocoder to limit search results to addresses located in Philadelphia.
The filter limits search results to items that have a place feature of 'Philadelphia' or a district feature of 'Philadelphia County'.  The bounding box limits search results to a rectangular area around Philadelphia, PA so that the search doesn't return results from other places named Philadelphia, such as Philadelphia, Mississippi.
This closes issue #629
> 629: Limit Search to Philadelphia

- src/components/SidePanelControlBar.tsx
This PR addresses issues #654 and #627 
For issue 654:
Two screen-reader-only spans have been added to the filter button label so that a screen reader can announce the filter button with the number of filters currently applied.  When no filters are applied it announces 'Filter button'.  When 2 filters are applied, it announces 'Filter button 2 filters applied'.  To allow the screen reader to read the label in that order, the aria-label property was removed and the default 'Button' announcement is overridden by adding `aria-roledescription=' '`
For issue 627:
The 'if' statement has been removed from the filtuer button's onPress function so that the focus stays on the filter button when filter view is toggled off.
To test:
- go to the Find Properties page
- using a screen reader, TAB to the …
> 654: Announce Number of Filters & 627: Keep Keyboard Focus on Filter Button

- src/app/FilterProviderWrapper.tsx
- src/app/find-properties/[[...opa_id]]/page.tsx
- src/app/layout.tsx
- src/components/Filters/DimensionFilter.tsx
- src/components/SidePanelControlBar.tsx
This addresses issue #685 
The selectedPanelKeys state, which controlled the appearance of selected panel filters is not saved when you toggle back and forth between the filter view and property cards view.  To keep the panel filters correctly selected after toggling the view, the initial 'selectedPanelKeys' state is now generated from appFilter.
This is an example of the corrected panel filter appearance after toggling between the filter view and property cards view:
> 685: Bug Fix: Selected Panels 'Selected' State

- src/components/SinglePropertyDetail.tsx
Acceptance Criteria
- add <aria-label="Atlas, opens in a new tab"> on the Atlast link.
Acceptance Criteria Finished
- add <aria-label="Atlas, opens in a new tab"> on the Atlast link.
Closes #659
> Issue 659: Add aria label to ThemeButtonLink

- src/components/SinglePropertyDetail.tsx
- Changed the bookmark icon for saving a property to a check icon.
- Screenshoots:
https://github.com/CodeForPhilly/clean-and-green-philly/assets/88219993/8d7ed789-9702-490f-b355-eaab0fc07130
> Fix issue 646 change saved btn icon

- src/components/IconLink.tsx
Refactored the value of aria-current from "true" to "page" as the description requested. 
Closes #660
> Issue 660: Add aria label to IconLink

- src/app/(content-pages)/accessibility-statement/AccessibilityStatementPage.tsx
- src/app/(content-pages)/accessibility-statement/layout.tsx
- src/app/(content-pages)/accessibility-statement/page.tsx
- src/app/(content-pages)/vpat/VPATPage.tsx
- src/app/(content-pages)/vpat/layout.tsx
- src/app/(content-pages)/vpat/page.tsx
- src/components/Footer.tsx
- Created two pages: `/accessibility-statement`, `/vapt`.
- Plain html `<table>` tags were used to ensure accessibility. Tested with VoiceOver on Mac - the web content is screen-readable.
- Examplary screenshots (Only partial content on `/vapt` page were captured as the page is long).
Closes #698
> Issue 698: Add a11y page

- src/components/CookieConsentBanner.tsx
- src/context/CookieContext.tsx
#701 
This resolves the cookie banner re-rendering by recording/checking the user's local storage.
The issue can be recreated by: 
- running localhost
- take action on cookie banner, either accept or decline
- refresh tab, or open new tab and the cookie banner should re-render
> Issue 701: cookie banner re-rendering

- src/app/layout.tsx
This PR updates Clean & Green Philly's social media metadata to use a production URL instead of staging URL.
Related to issue #588 and PR #684.
> 588: Use production URL for Open Graph metadata

- data/src/classes/backup_archive_database.py
- data/src/classes/diff_report.py
Copy the tiles files to backup instead of rename so we save original files in the base dir if they are used.
> Copy tiles file to backup/ instead of move

- src/app/not-found.tsx
This adds a custom 404 page.
It adds not-found.tsx to src/app/.
The navbar will still be present.
It has a return to home link. 
It should work for any incorrect url.
Addresses ticket #700
> Issue 700: Add custom 404 page

- src/components/PropertyDetailSection.tsx
- src/components/SidePanelControlBar.tsx
This PR addresses issue #318. Changed "Properties In View" to "Total Properties" and added item count.
> Fix #318: Renamed "Properties in View" and added item count 

- src/components/PropertyDetailSection.tsx
This PR closes issue #656 
Adds an 'aria-current' attribute to the pagination page buttons.
To test, use a screen reader and navigate to the pagination buttons at the bottom of the property list view of the 'Find Properties' page.
- On pressing an unselected page button, the screen reader should announce, "Current page, page #".
- If you navigate away from the selected page button and then navigate back to it, the screen reader should announce, "Page # button, current page".
> Add aria-current to page buttons

- src/components/PropertyDetailSection.tsx
This PR addresses issue #657. Added aria-live element that announces "You are on page #" after updating pagination.
> Fix #657: Added aria-live to find properties results 

- src/app/(content-pages)/methodology/MethodologyPage.tsx
This PR closes issue #650 
I moved the `<span>`s that serve as targets of the two "learn more" links so that they are immediately above the headers of the sections they are related to.  Visually, the linked-to headers are brought to the top of the Methodology page, and screen readers now announce the header, rather than the previous paragraph.
Question for @bacitracin :  I'm still using the `<span>`s so that the screen reader reads the text of the header and then stops.  I could delete the `<span>`s and instead add `id=...` to the `<div>` containing the header and paragraph text, which was suggested as a possible alternative solution to this issue.  I tested it and the navigation works the same either way.  However, if I add the `id` to the `<div>`, the screen reader reads the header and …
> Moved "learn more" link fragment spans to be above subject header

- docs/SETUP/BACK_END.md
Fixes #730. 
Spelling corrected.
> Bug Fix for 730: Fixed typo in BACK_END.md to correct spelling of the word "recommended"

- src/app/(content-pages)/transform-property/TransformPropertyPage.tsx
- src/app/globals.css
- src/components/ContentCard.tsx
- tailwind.config.ts
Issue #619
old pr: https://github.com/CodeForPhilly/clean-and-green-philly/pull/713
Make blue links darker to pass contrast color ratio. Adds new dark blue color and swap out all blue links to use new 900 blue.
> 619: Change tailwind config and add new contrast friendly blue

- src/app/find-properties/[[...opa_id]]/page.tsx
- src/components/PropertyDetailSection.tsx
- src/components/PropertyMap.tsx
This PR is for this task: Show error message if map fails to load #712
https://github.com/CodeForPhilly/clean-and-green-philly/issues/712
To view the error state go to the find properties page, open dev tools, and block the URL from google storage to simulate a failed API call.
On page reload, this error message will be displayed on the property details panel.
I think the automatic prettier formatting makes it seem like a lot of lines of code have been changed. But most of these lines are minor changes in formatting. If it would be better for the PR I can redo do these changes with out any of the formatting changes and resubmit.
> Michael dratch/712 error message if map fails to load

- src/components/SinglePropertyDetail.tsx
This closes issue: https://github.com/CodeForPhilly/clean-and-green-philly/issues/623
At first I was going to edit the ThemeButton component but I think that might cause a lot of reworking and it seems like there are some changes coming to the navigation buttons so I added a conditional aria-pressed label for now.
> 623-saved-button-aria

- .eslintrc.json
- src/app/find-properties/[[...opa_id]]/page.tsx
- src/components/ContentCard.tsx
- src/components/Header.tsx
- src/components/Hotjar.tsx
- src/components/MapLegendControl/MapLegendControl.tsx
- src/components/PropertyCard.tsx
- src/components/PropertyDetailSection.tsx
This PR addresses issue #822 where merged PRs are failing to deploy to Vercel's preview and production environments. It appears that `npm run build` is failing due to new plugins recently added to .eslintrc.json. These plugins appear to enforce strict TypeScript-ESLint rules.
This PR reduces the severity of two common TS rules. ESLint now issues a warning instead of throwing errors for them:
- @typescript-eslint/no-explicit-any
- @typescript-eslint/no-unused-vars
This PR also removes some unused variables.
Before reducing the rules' severity, running `npm run lint` in local env produced these errors:
After reducing their severity, running `npm run lint` produced warnings instead of errors:
> 822: Fix deployment failure bug

- package.json
- src/components/Filters/MultiSelect.tsx
This PR reverts mapbox-gl from v3.5.2 back to v3.2.0 due to breaking changes. These changes were causing `npm run build` to fail, thus causing the failure of deployment to Vercel's preview and production environments. This PR addresses issue #822.
Before reverting mapbox-gl to v3.2.0, running `npm run build` in local env failed due to this error:
After reverting to v3.2.0, running `npm run build` resulted in a successful build:
After this PR was submitted, all GitHub checks passed:
A front-end issue will be created for updating mapbox-gl to v3.5.2. Whoever is assigned the issue will need to resolve breaking changes by refactoring some UI components. I will include details in the issue.
> 822: Fix deployment failure bug — revert mapbox-gl to v3.2.0

- .github/release-drafter.yml
This PR addresses #767 by fixing an issue with release version and tag numbers
rendering incorrectly. This PR changes `release-drafter`'s templates for release names and tags
to render them as "v2.0.0" instead of "v2.0.0.1.1.0.1.0.1".
> 767: Fix issue with release version number

- .pre-commit-config.yaml
- docs/SETUP/BACK_END.md
- docs/SETUP/FRONT_END.md
- package-lock.json
Address precommit hook for formatting, linting, and deps checks on front and back ends. Uses `ruff` for backend formatting and linting and `pipenv` for backend deps checks; on front end, uses `prettier` for formatting, `eslint` for linting, and `npm` for deps audit.
Closes #759
> Add precommit hook

- data/docker-compose.yml
prevent builds from completing if they throw formatting or linting errors (previously exited with code 0 regardless)
> fix docker formatting and linting

- src/app/(content-pages)/accessibility-statement/AccessibilityStatementPage.tsx
- Added aria-hidden="true" to `<hr>` element on a11y statement page.
Closes #858
> Remove hr from Screen Reader

- src/app/(content-pages)/accessibility-statement/AccessibilityStatementPage.tsx
- Fixed typos and wording in Accessibility Statement Page.
Closes #857
> fix typos in a11y statement

- src/components/Footer.tsx
- Fixed issues regarding footer accessibility: `<ul>` only contains `<li>` elements; `aria-hidden="true"` for dashes
Closes #856.
> fix footer a11y issue

- src/app/(content-pages)/methodology/MethodologyPage.tsx
This PR addresses issue #878 where the GitHub repository link on the Methodology page was incorrectly redirecting users to a Figma page. The link now correctly directs users straight to the GitHub repository without the intermediate Figma redirect.
- Updated the hyperlink under the Data Sources header on the Methodology page to point directly to the GitHub repository
> Fix GitHub repository link redirect issue on Methodology page (#878)

- data/src/data_utils/negligent_devs.py
This PR fixes a glitch in how negligent developers were being ID'd, stemming from inadequate string cleaning before a join. It also adds property counts for city agencies, distinguishing them from private property.
> fix issue with how negligent devs are identified

- data/src/Pipfile
- data/src/Pipfile.lock
- data/src/data_utils/park_priority.py
- data/src/test/test_data_utils.py
Add functionality to dynamically determine parkserve URL before loading data. Includes:
- new function to scrape URL and download data
- progress printing
- unit tests
Addresses #705
> Dynamically determine parkserve URL

- src/app/(content-pages)/page.tsx
This request:
1. Changes Pennsylvania Horticulture Society to Pennsylvania Horticultural Society on homepage.
2. Creates a hyperlink for the text Pennsylvania Horticultural Society to https://phsonline.org/
> Azbl/875 Fix and hyperlink PA horticultural society on homepage.

- data/Dockerfile-pg
- docs/SETUP/BACK_END.md
@jinks145 found that when trying to build the postgres container, the postgis version in Dockerfile-pg was no longer supported.   I reproduced the error:
E: Version '3.4.3+dfsg-1.pgdg110+1' for 'postgresql-16-postgis-3' was not found
I updated the version to 3.4.3+dfsg-2.pgdg110+1 per his suggestion which allowed the build to complete.
I also made some small tweaks to the backend setup doc.
> fix postgis version, update backend docs

- src/app/(content-pages)/donate/DonatePage.tsx
- src/app/(content-pages)/donate/layout.tsx
- src/app/(content-pages)/donate/page.tsx
- src/components/Header.tsx
- src/components/MobileNav.tsx
addresses #948 
Ideally, I'd like to embed the FundRazer donation widget, but was having issues getting it to play nicely with react. Maybe for someone else to do another time.
> feature request 948: set up donation page

- data/src/constants/services.py
- data/src/data_utils/phs_properties.py
- data/src/data_utils/priority_level.py
The PHS land care and community land care datasets have been merged into a single dataset. This fix updates our `constants` file to reflect the new URL, and also changes the priority level ranking to use a spatial join instead of opa join, since the PHS data no longer include OPA ID (this is annoying).
> Fix for a glitch caused by changes to PHS data

- src/components/Filters/ButtonGroup.tsx
- src/components/Filters/DimensionFilter.tsx
- src/components/Filters/MultiSelect.tsx
- src/components/Filters/Panels.tsx
This resolves issue https://github.com/CodeForPhilly/clean-and-green-philly/issues/663
- role of checkbox added to the button group elements
- aria-describedby is used to tie in heading to the checkbox element and the multi-select
> 663 checkbox behavior

- package-lock.json
- package.json
- src/components/MapLegendControl/MapLegend.tsx
- src/components/PropertyMap.tsx
Removed Mapbox dependencies by replacing Mapbox Geocoder with MapTiler GeocodingControl, restoring the Geocoding Control functionality Updated package-lock.json dependencies to remove mapbox-gl dependencies and pass precommit hook.
https://docs.maptiler.com/react/maplibre-gl-js/geocoding-control/
Fixes #864
> Replace mapbox geocoding control with maptile geocoding control

- src/components/FilterView.tsx
- src/components/SidePanelControlBar.tsx
- src/components/ThemeButton.tsx
This resolves issue https://github.com/CodeForPhilly/clean-and-green-philly/issues/625
The button when activated has aria-expanded when selected. The focus skips the Download button and goes directly to the "X" button in the side panel.
> Amberroseweeks 625 improve filter button

- data/Dockerfile-timescale
- data/docker-compose.yml
- data/init_pg_timescale.sql
- docs/SETUP/BACK_END.md
Adds timescaledb and pg_stat_statement extensions for postgres. See #997 for detailed discussion. For now, the timescale extension is installed in a separate container with postgres listening on port 5434. This may be consolidated with the existing postgres container in the future.
> Add timescale and pg_stat_statement postgres extensions

- src/app/globals.css
- src/components/Header.tsx
- src/components/IconLink.tsx
This PR introduces changes in the spacing and layout of the navbar items to achieve better alignment. Addresses [(Issue#1020)](https://github.com/CodeForPhilly/clean-and-green-philly/issues/1020#issuecomment-2543431067) 
---
1. You should be able to see the header upon loading the app.
2. The style changes should be in-line with what's mentioned in the original issue.
3. The styling should be consistent across selected and hover states.
---
> Fixes Styling Issues Within Header

- src/app/globals.css
- src/components/PropertyMap.tsx
This PR removes the map scale on the bottom left of the property map and hides the map attribute on the bottom right of the map by default.  Addresses [(Issue#1022)](https://github.com/CodeForPhilly/clean-and-green-philly/issues/1022#issuecomment-2543404412) 
---
1. Navigate to the Property Map
2. You should not see the map scale on the bottom left corner of the map just the map legend
3. The attribution on the bottom right should be hidden when the application loads
---
> Hides extra map elements

- src/components/ThemeButton.tsx
Description
This PR resolves an error that occurs when opening the app.
Error:
Warning: Invalid ARIA attribute 'ariaCurrent'. Did you mean 'aria-current'?
Cause:
The error is linked to an issue detailed in [NextUI v2.6.0](https://nextui.org/blog/v2.6.0).
Steps to Test
Launch the app.
Check the console log for errors.
Confirm that the ariaCurrent warning no longer appears.
> Fixes aria error

- src/app/globals.css
Changes requested in #1079 to unify mobile styles across screenwidths. 
Hover styles for the mobile menu items below the `max-sm` screenwidth (640px) were being overridden by a tailwind rule applied to the `iconLink` css class. Removing that rule restored them.
https://github.com/user-attachments/assets/436f2ff8-1924-4e01-8817-c6fbd44c7b33
https://github.com/user-attachments/assets/abdc9c0e-c6a5-433c-9b00-7acfd27cdf24
1. Navigate to the prod site at https://www.cleanandgreenphilly.org/
2. Observe the site at a screenwidth of more than 640px, and less than 850px.
3. Click on the mobile nav toggle (the hamburger icon in the nav bar)
4. With the mobile nav open, hover over the nav items. There should be a light gray background behind items.
5. Observe the site at a screenwidth of less than …
> Allow hover styles on screens below 640px

- src/components/MobileNav.tsx
The mobile hamburger menu is not currently accessible either by keyboard or screenreader, per issue #978 . 
As noted by @bacitracin in #978 , the required change is extremely simple. We just add a `tabIndex` onto the mobile nav toggle and the browser takes care of the rest.
I've added a comment to the ticket which follows this one, #979 , but the menu items for the mobile menu are accessible via tab...but only at the very very end of the tab order, past the bottom of the page. This is because the mobile menu is loaded into the html at the very end of the document, in spite of being located within the `Header` component in the React code. I don't know why this would be! Possibly not an issue since we want to access them via keyboard up-down arrows anyway, but thought it would be worth …
> Add tabIndex to mobile nav toggle

- .github/workflows/flag-stale.yml
#1090 
Updated the [flag-stale.yml](https://github.com/CodeForPhilly/clean-and-green-philly/blob/main/.github/workflows/flag-stale.yml) file to stop adding the 'stale' label to issues.
> TASK [#1090] : Stop GitHub Actions from adding "stale" labels to issues

- src/components/SidePanelControlBar.tsx
This PR fixes a bug, #1024, where clicking on filtering options from the Find Properties page causes the focus to move to the top.
Not having currentView in the dependency array caused the useEffect to run on every render. Adding currentView as a dependency ensures that the re-render is triggered only when the currentView state changes.
1. Navigate to 'Find Properties'
2. Click on the 'Filter' button
3. If you click on any filtering action on the page, the focus should remain at the point where the action occurred.
https://github.com/user-attachments/assets/2290409e-a431-4340-bf73-c59cf94a26ab
> Bugfix - prevent losing focus when filtering

- .github/auto_assign.yml
Removes an inactive reviewer to prevent unnecessary notifications.
Uses `null` instead of entirely deleting the line to allow for easier future modifications.
Closes #1089 .
> Task 1089 remove inactive reviewer

- src/components/PropertyMap.tsx
Initially, closing a property's tooltip popup on the map did not simultaneously navigate the right pane from property details to all properties in the current neighbourhood, or vice versa. This PR fixes that issue.
Additionally, the property ID in the URL is now removed when the property is deselected.
This PR addresses issue #1025 
https://github.com/user-attachments/assets/c6eb8a90-1b94-4100-a8fd-c89f455c2c90
> Fix: Closing tooltip popup on map closes property details

- package-lock.json
- package.json
Update the lockfile to fix the security vulnerability affecting `cross-spawn` versions `7.0.0 - 7.0.4`. The flagging module was a transitive dependency of `cross-spawn` being built within the `npm` module, so `npm update npm` was enough to fix the issue, but I also included an override component in the `package.json` to prevent that module from being rebuilt in the event of any issue with needing to generate the lockfile.
This PR also includes audit fixes to the lockfile from several other medium level security issues that were outstanding and flagged by the precommit hook.
This PR addresses issue #1038 
I pulled a fresh repo and `npm update npm` , `npm audit fix`, and then `npm install` to build the project modules, and this was enough to push the versions of `cross-spawn` appearing the …
> Cross-spawn Vulnerability Fix and Other Audit Fixes

- data/src/new_etl/data_utils/pwd_parcels.py
- data/src/test/test_data_utils.py
Previously in the new ETL pipeline retained geometries would get misaligned due to mismatched indexes (gapped vs contiguous).
In the new ETL pipeline, an index with gaps was updated by a df with a continuous index by location using `combine_first` which caused geometries to get associated with the wrong properties when polygon/multi-polygons were not available.
I refactored the pwd_parcels to have additional helper functions (transform, merge) to allow easier testing.
An alternative implementation may be a bit cleaner but doesn't avoid using `combine_first` but instead uses it safely (on the same df so the index is guaranteed to be the same).
```
merged_df = primary_featurelayer_gdf_unique_opa_id.merge( …
```
> Fix: 1159 merge on opa_id in pwd_parcels

- data/src/main.py
- data/src/new_etl/data_utils/community_gardens.py
- data/src/new_etl/validation/__init__.py
- data/src/new_etl/validation/access_process.py
- data/src/new_etl/validation/base.py
- data/src/new_etl/validation/city_owned_properties.py
- data/src/new_etl/validation/community_gardens.py
- data/src/new_etl/validation/council_dists.py
- data/src/new_etl/validation/kde.py
- data/src/new_etl/validation/li_violations.py
- data/src/new_etl/validation/nbhoods.py
- data/src/new_etl/validation/owner_type.py
- data/src/new_etl/validation/phs_properties.py
- data/src/new_etl/validation/ppr_properties.py
- data/src/new_etl/validation/rco_geoms.py
- data/src/new_etl/validation/tree_canopy.py
- data/src/new_etl/validation/vacant_properties.py
Please include a summary of the change or the feature being introduced. Include relevant motivation and context. If necessary, list any dependencies that are required for this change.
This PR addresses issue #...
Please describe and/or document how you verified your changes. If relevant, include details of the testing environment and the tests you ran to see how your change affects the code.
> Add data validation framework with vacant properties validator

- src/app/find-properties/[[...opa_id]]/page.tsx
- src/components/FilterView.tsx
841d18c refactor: remove unused `updateCurrentView` callback
9ab43e0 feat: update reset button to dispatch 'CLEAR_DIMENSIONS'
4f94faf feat: change the 'X' button to say 'Reset'
This PR replaces the `X` button with a `Reset` button that dispatches an event to clear filter state
This PR addresses issue #1196 
https://github.com/user-attachments/assets/984f890a-fdd2-4604-947d-31c12747c4e2
> [1196] Filter reset button

- data/src/data_utils/city_owned_properties.py
- data/src/data_utils/council_dists.py
- data/src/validation/base.py
- data/src/validation/city_owned_properties.py
- data/src/validation/council_dists.py
As part of the larger data pipeline validation implementation, this PR creates custom schemas/validators for external data sources, namely council districts and city owned properties. When running these two stages of the data pipeline, their base validation functions will call their custom validations and schema checks, which make up the content of these two files. 
Note that geometry validator is already being called by the base validator so we don't need to include that in the new code. 
This PR addresses issues #1237 and #1238 
I reran the pipeline with changes to ensure no new errors or warnings were being displayed for the affected pipeline stages. I also created a local script with fake data to ensure the …
> External input validator

- src/app/find-properties/[[...opa_id]]/page.tsx
This PR fixes a user experience issue where selecting a property on the map wouldn't show the property details if someone was currently viewing the filter panel.
The fix automatically switches from the filter view to the property details view whenever someone clicks on a property on the map. Now when users are filtering properties and then click on one they're interested in, they immediately see the property information without having to navigate away from the filters first.
> Fix filter view not switching to property details when map property is selected
