CodeForPhilly/clean-and-green-philly

data/src/classes/featurelayer.py, data/src/data_utils/rco_geoms.py
I missed the step where I needed to aggregate the `rco_info`. Added that in this PR.
=> collapse rco data

src/app/components/Filters/DimensionFilter.tsx
Lol @ the tiny PR--just getting comfortable changing filter styling
=> Update filter button colors

package-lock.json, package.json, src/app/components/PropertyMap.tsx
Tiles not rendering properly yet--I think it's because I haven't figured out how to load them correctly. 
Some docs here:
https://gispofinland.medium.com/we-recently-implemented-an-open-source-outdoor-map-service-buzzwords-serverless-vector-tiles-ac132e1f60bb
https://visgl.github.io/react-map-gl/docs/get-started/adding-custom-data
https://visgl.github.io/react-map-gl/docs/api-reference/layer
https://docs.mapbox.com/style-spec/reference/sources/
https://docs.mapbox.com/style-spec/reference/sources/#vector
https://github.com/visgl/react-map-gl/blob/master/docs/api-reference/source.md
=> start refactoring map in react-map-gl; tiles not rendering properly yet

PROJECT_BACKGROUND.md
=> add basic reading list for new contributors

package-lock.json, package.json, src/app/components/GeocoderControl.tsx, src/app/components/PropertyMap.tsx
=> get search bar working via mapbox geocoder api

SETUP.md
There was a small typo when following instructions in SETUP.md
=> Cleans SETUP.md

data/src/data_utils/nbhoods.py, data/src/script.py
=> add neighborhoods to dataset

data/src/constants/services.py, data/src/data_utils/city_owned_properties.py, data/src/data_utils/opa_properties.py, data/src/data_utils/phs_properties.py, data/src/script.py
Renaming/adding/trimming fields needed for conditional logic for property access. Addresses #12 (but doesn't close it completely)
=> Clean fields for property access conditional logic

data/src/config/config.py, data/src/data_utils/access_process.py
@nlebovits I believe I fixed this, take a look. here are the final counts:
=> 163 fix access process script

src/app/components/AboutPage.tsx, src/app/components/Footer.tsx
=> fix gmail addresses

data/src/data_utils/access_process.py, data/src/data_utils/drug_crimes.py
=> fix script to account for non-PLB, city-owned land

data/src/constants/services.py, data/src/data_utils/drug_crimes.py, data/src/script.py
=> add module for drug crime KDE

src/app/components/SidePanelControlBar.tsx
=> change to using just the table view for vacant properties

src/app/components/SinglePropertyDetail.tsx, src/app/components/SinglePropertyInfoCard.tsx, tailwind.config.ts
This PR adds styling and additional content to the sidebar.
Future work will be required to add the link for RCO and Council District.
=> 214 style sidebar

src/app/components/SinglePropertyDetail.tsx
=> add property type attribute in single property detail table

src/app/components/TransformPropertyPage.tsx
#313 
-Fixed Detroit Future City quiz link so now it's a functional link.
-On initial commit accidentally changed formatting of Soil Generation link so this was restored to original
=> fix detroit future city quiz link

src/app/components/PropertyDetailSection.tsx
This PR adjusts the accessibility of the navigation per #204.
=> feat: Update navigation accessibility

src/app/components/AboutPage.tsx, src/app/components/MethodologyPage.tsx, src/app/components/RequestRemovalPage.tsx, src/app/components/SinglePropertyDetail.tsx, src/app/components/TransformPropertyPage.tsx, src/app/globals.css
This PR underlines all links on the static pages, per #268.
=> feat: underline links

src/app/components/MethodologyPage.tsx
Reduced MethodologyPage to 1 column for small screens and decreased left/right padding on small/medium screens to improve responsiveness/mobile experience.
=> Improved responsiveness for small screens for Methodology Page

src/app/components/Footer.tsx
This PR updates the footer markup for accessibility per #201.
=> fix: Update footer markup structure for accessibility

src/app/components/Header.tsx, src/app/components/IconLink.tsx
Resolves #206 and makes progress in #205 (the nesting of the buttons and links is resolved).
=> feat: Improve keyboard focus styling

src/app/components/SinglePropertyDetail.tsx
using aria-label to add a unique name to two tables within the SinglePropertyDetail.tsx file. 
This closes issue https://github.com/CodeForPhilly/vacant-lots-proj/issues/362
=> 362-unique-table-name

.vscode/settings.json, src/app/components/Header.tsx, src/app/components/IconLink.tsx, src/app/globals.css, tailwind.config.ts
Issue: https://github.com/CodeForPhilly/vacant-lots-proj/issues/344
Because of the site redesign some a11y issues no longer apply for desktop. I'd like to create a separate issue for mobile. For now I updated the desktop styling to match the new design. 
**Updated Colors**
- Added the gray-900 and updated gray-100 in the tailwind.config to match colors in Figma.
**IconLink Component:** 
- I changed this component to write a function to check if the NavbarItem isActive or not based on the url and pathname. If so isActive will be applied.
- I added aria-current to the Navbar item so it would read whether or not the user is on the current page depending on if the href matches the pathname. 
- If the NavbarItem isActive then the class active-state-nav will change the text color to green-700 …
=> Iss344: A11y: Fix “Take Action” and “About” menu accessibility issues #344

src/app/components/GetAccessPage.tsx, src/app/components/TakeActionOverviewPage.tsx, src/app/components/TransformPropertyPage.tsx
Reverts CodeForPhilly/vacant-lots-proj#402
=> Revert "Jgaye/261 handle sizing of take action pages"

src/app/components/MethodologyPage.tsx
=> bug(438) - Fixed DATASETS.md link

docs/SETUP/FRONT_END.md, docs/SETUP/FULL_SETUP.md
=> Maptiler docs

src/app/(content-pages)/page.tsx, src/app/find-properties/page.tsx, src/components/FilterView.tsx, src/components/InfoGraphicSection.tsx, src/components/SidePanelControlBar.tsx, src/components/SinglePropertyDetail.tsx, src/components/ThemeButton.tsx, tailwind.config.ts
#288 
- Created new `ThemeButton` and `ThemeButtonLink` to be used across the app for button consistency.
- Replaced all buttons (exclude nav buttons) with the new `ThemeButton` for regular buttons or `ThemeButtonLink` for links
- `ThemeButton` shows as `<button>` with `type="button"`
- `ThemeButtonLink` shows as `<a>` with `role="link"`
#449 
- Updated some buttons to be primary buttons (`Learn How` and `Get Started` buttons on the landing page)
All Button States
https://github.com/CodeForPhilly/vacant-lots-proj/assets/33296817/93cc6247-b745-44a7-8443-d240c078ef09
Button vs ButtonLink in DOM
https://github.com/CodeForPhilly/vacant-lots-proj/assets/33296817/985944ab-97c3-45a4-b7de-e8cb05b96e91
```
<div className="flex justify-center items-center gap-2 my-2">
<ThemeButton label="Primary" …
```
=> #288 and #449 Fix Button Inconsistency and Update Some Buttons to Primary

src/components/SidePanelControlBar.tsx
Adds the filtered count to filter button, with active state if any filters are applied
https://github.com/CodeForPhilly/vacant-lots-proj/assets/8061917/3f3fc6ee-81c6-4f94-b7af-e643ef1d82fb
Closes #457
=> feat(457): add filtered count to button

src/components/SinglePropertyDetail.tsx
Adds a white background to the sticky Back button
https://github.com/CodeForPhilly/vacant-lots-proj/assets/8061917/eabfd9ba-db05-40ce-a591-f448964d1958
=> feat(395): add white background to sticky back button

src/app/(content-pages)/get-access/GetAccessPage.tsx
**This request updates the content and formatting of the Get Access page.** 
1. Text is updated to represented latest prototype
2. "Cards" are created with blue / gray backgrounds and icons
3. Accordion is removed 
To consider: GetAccessCard component (as of now all changes were made on GetAccessPage.tsx).
Also, this request did not address the functionality of hyperlinks included in this page.
=> 429 Update Info Cards on Get Access Page

src/app/globals.css, src/components/Header.tsx, src/components/MobileNav.tsx
This PR addresses issue #477. I fixed few small inconsistencies including the dropdown position.
https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/2fc1a552-1b0b-43be-9200-3703a7e6800f
https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/34f4d7a3-a16d-4eb4-b930-2ab3990a13ad
=> Fix #477: Updated navbar for breakpoints between 640px and 850px

src/components/PropertyCard.tsx
This PR addresses issue #503.
https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/c8b2fada-9033-447b-a201-d68d3bedbd1c
=> Fix #503: Updated property card styling

src/app/(content-pages)/about/AboutPage.tsx, src/app/(content-pages)/get-access/GetAccessPage.tsx, src/app/(content-pages)/layout.tsx, src/app/(content-pages)/legal-disclaimer/LegalDisclaimerPage.tsx, src/app/(content-pages)/methodology/MethodologyPage.tsx, src/app/(content-pages)/page.tsx, src/app/(content-pages)/request-removal/RequestRemovalPage.tsx, src/app/(content-pages)/take-action-overview/TakeActionOverviewPage.tsx, src/app/(content-pages)/transform-property/TransformPropertyPage.tsx
This PR addresses issue #526 & #534. 
https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/4bedf2ab-2a65-44f7-96b2-0e7c82ca7d61
=> Fix #526, #534: Content pages resize consistently 

src/app/(content-pages)/gentrification/GentrificationPage.tsx, src/app/(content-pages)/gentrification/layout.tsx, src/app/(content-pages)/gentrification/page.tsx
This creates the Gentrification page to match the prototype.
- Creates gentrification directory in (content-pages) which contains GentrificationPage.tsx, layout.tsx, page.tsx
=> Created Gentrification Page

src/app/globals.css, src/components/PropertyCard.tsx, src/components/PropertyMap.tsx, src/utilities/toTitleCase.ts
This PR is a fix for issue https://github.com/CodeForPhilly/vacant-lots-proj/issues/502 — ROUND 3
=> Styling: Improve Property Tooltip (502-3)

src/app/globals.css, src/components/PropertyAccessOptionContainer.tsx, src/components/PropertyMap.tsx
Fixed the tooltip on staging to match the figma spec.
=> fix(502): fix map tooltip

data/src/data_utils/rco_geoms.py, src/components/PropertyMap.tsx
fix issue with RCO filters when others are activated
=> Filter fix 42124

src/components/SinglePropertyDetail.tsx
=> add zoning to property detail

src/app/find-properties/[[...opa_id]]/page.tsx
This PR adds a close download pane button
https://github.com/CodeForPhilly/vacant-lots-proj/assets/8061917/d07ff504-a152-4438-8558-6c632d358736
https://github.com/CodeForPhilly/vacant-lots-proj/issues/535
=> feat(535): add close download view button

src/components/SinglePropertyDetail.tsx
https://github.com/CodeForPhilly/vacant-lots-proj/issues/544
=> feat(544): adjust remove property section

docs/CONTRIBUTING.md
Added sections to part of contributing doc and itemized steps. Idea is for new devs to be able to easily understand flow from issue > prod. 
This PR addresses issue #634.
N/A, seeking feedback on edits.
=> Add sections to contributing, clarify CI/CD steps

src/components/Filters/DimensionFilter.tsx
This PR addresses issue #649 .
=> Fix #649: Updated aria-labels for learn more links in filter

src/components/SidePanelControlBar.tsx
=> Fix #655: Added aria-expanded for download button

data/Dockerfile, data/Dockerfile-pg, data/docker-compose.yml, data/init_pg.sql, data/src/Pipfile.lock, data/src/classes/diff_report.py, data/src/classes/featurelayer.py, data/src/config/config.py, data/src/data_utils/dev_probability.py, docs/SETUP/BACK_END.md
Postgres is now run in it's own container.  Postgis installation is also done automatically through Docker.  Native install no longer needed.
=> Issue 630: Dockerize postgres

data/docker-compose.yml, data/src/classes/backup_archive_database.py, data/src/classes/diff_report.py, data/src/classes/featurelayer.py, data/src/data_utils/park_priority.py, data/src/data_utils/ppr_properties.py, data/src/data_utils/utils.py, data/src/script.py, data/src/test/test_data_utils.py, docs/SETUP/BACK_END.md
This PR includes some small fixes for the new feature layer classes, the backup logic and the diff report.  There is no issue associated with these bugs.  I found these while setting up the code on my GCP vm.
=> fixes for back-end

.github/workflows/pr_checks_backend.yml, .vscode/settings.json
Addresses #638 . Adds a test to confirm that the primary docker container builds correctly when any files are changed in `data`. Probably would be good to also add checks for the `postgres` container.
=> get pr_checks_backend.yml working

docs/CONTRIBUTING.md
=> add quickstart checklist to contributing guide

src/app/(content-pages)/accessibility-statement/AccessibilityStatementPage.tsx
- New VPAT link format : You can find our [full evaluation report in VPAT®️ format.](https://www.cleanandgreenphilly.org/vpat)
Closes #870.
=> adjust link for a11y

src/components/InfoGraphicSection.tsx
**Description**: This pull request addresses the issue of inconsistent image corner rounding on the homepage, as outlined in Task #876. It was observed that two images on the homepage were not following this design requirement.
**Changes**: The fix involved wrapping the image component in a div element with padding to maintain consistent spacing
**Testing**: Manually tested the homepage to verify that the images are correctly rounded and displayed.
=> task: Ensure image corners are rounded consistently

README.md
Updating the Contributor section in the READ.ME file to where the title is more accurate to being a Point of Contact section for new users.
=> Update Contributor Section in READ.ME

docs/DATASETS.md
=> update data dictionary

data/src/data_utils/l_and_i.py
=> filter li complaints and violations for only blight-related instances

src/components/FilterView.tsx, src/components/PropertyCard.tsx, src/components/PropertyDetailSection.tsx, src/components/SinglePropertyDetail.tsx
- update PHS and gun crimes details
- remove private/public ownership filter
=> Front-end fixes

data/src/data_utils/negligent_devs.py
fixes an issue with negligent devs being calculated improperly due to null values vs. empty strings (now handles both cases)
=> fix issue with empty strings

data/src/data_utils/kde.py
=> quick fix for labeling percentiles issue

.github/dependabot.yml
=> disable dependabot autoupdates for pip

data/src/classes/featurelayer.py, data/src/constants/services.py
=> restore deleted files from src/

data/src/main.py
This PR addresses issue #1139 
I think I made a change to appease the linter when making my commit and must not have been careful enough.
=> chore: add missing imports to new ETL pipeline

src/app/(content-pages)/get-access/GetAccessPage.tsx
This addresses issue #1167 and updates the PLB link in the Get Access page to their new site.
=> Update PLB Link

src/components/PropertyMap.tsx
I applied the "hand grab" styling to the cursor when it enters the map while still maintaining the "pointer" while hovering over properties. This used the changeCursor function.
This PR addresses issue #1188 
I clicked, hovered, and dragged on the map several times to make sure all cases worked.
=> Nick magidson/1188 apply hover styling on map

data/src/config/config.py, data/src/data_utils/park_priority.py, data/src/data_utils/pwd_parcels.py, data/src/test/test_data_utils.py, data/src/test/test_validation.py
This PR fixes the broken unit tests for the Park Priority area dataset, plus some minor changes to PWD parcels. It also separates out unit testing from the validation framework so unit tests don't automatically turn into integration tests.
This PR addresses issue #1249.
=> test: fix tests for parkserve, pwd parcels
